import ReduxProvider from '@/redux/provider'
import NavBar from './components/navBar'
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex justify-center bg-black overflow-y-auto h-screen ">
          <div className="justify-center w-[350px] bg-emerald-50 overflow-y-auto hide-scrollbar sm:w-full">
            <ReduxProvider>
              <NavBar />
              {children}
            </ReduxProvider>
          </div>
        </div>
      </body>
    </html>
  )
}
