import type { Viewport } from 'next'
import ReduxProvider from '@/redux/provider'
import NavBar from './components/navBar'
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  manifest: '/manifest.json',
}

export const viewport: Viewport = {
  themeColor: '#B6C4B5',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex justify-center bg-[#798B78] overflow-y-auto h-screen ">
          <div className="justify-center w-[350px] bg-mainBg overflow-y-auto hide-scrollbar sm:w-full">
            <ReduxProvider>
              <NavBar />
              {children}
            </ReduxProvider>
          </div>
        </div>
      </body>
    </html>
  )
}
